# Generated by Django 4.0.6 on 2023-02-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificatioin Date and Time')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificatioin Date and Time')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('edition', models.PositiveSmallIntegerField()),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='core.author')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
